application: l-cavy
version: 1
runtime: python27
api_version: 1
threadsafe: true

default_expiration: "5d"

builtins:
- appstats: on
- admin_redirect: on
- deferred: on
- remote_api: on

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

inbound_services:
- warmup

handlers:
- url: /favicon.ico
  static_files: cavy/static/img/favicon.ico
  upload: cavy/static/img/favicon.ico

- url: /robots.txt
  static_files: cavy/static/robots.txt
  upload: cavy/static/robots.txt

- url: /_gae_mini_profiler/static
  static_dir: flaskext/gae_mini_profiler/static

- url: /static
  static_dir: cavy/static

- url: .*
  script: cavy.run.app
